name: voice_changer_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: any
  flutter_localization: ^0.3.1
  get_it: ^8.0.3
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  in_app_review: ^2.0.10
  flutter_svg: ^2.0.16
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  open_settings_plus: ^0.4.0
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.6.0
  permission_handler: ^11.3.1
  base_ui_flutter_v1:
    path: ../base_ui_flutter_v1
  uuid: ^4.5.1
  blur: ^4.0.2
  video_player: ^2.10.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  record: ^6.0.0
  image_gallery_saver: ^2.0.3
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  carousel_slider_plus: ^7.1.1
  share_plus: ^11.0.0
  super_tooltip: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/cartoon/
    - assets/anim/
    - assets/celebrities_and_public_figures/
    - assets/game_and_pop_culture_icons/
#    - assets/video_test.MOV
    - assets/video_test.mp4
    - assets/audio_test.mp3

  fonts:
    - family: SFCompactDisplay
      fonts:
        - asset: assets/fonts/sf_compact_display/SF-Compact-Display-Regular.otf


    - family: Belanosima
      fonts:
        - asset: assets/fonts/belanosima/Belanosima-Regular.ttf